import { FiveHundred, Instagram, Telegram, Unsplash } from "@/components/Icons";

// ---------------------- change home data from here ------------------------
export const homeData = {
  hero: {
    image: "/homeImages/hero.JPG",
    title: "Hello!",
  },
  trophies: {
    image: "/homeImages/trophy.jpg",
    trophyItems: [
      { name: "8", image: "/trophies/8.png" },
      { name: "7", image: "/trophies/7.png" },
      { name: "6", image: "/trophies/6.png" },
      { name: "4", image: "/trophies/4.png" },
      { name: "2", image: "/trophies/2.png" },
      { name: "1", image: "/trophies/1.png" },
      { name: "3", image: "/trophies/3.png" },
      { name: "9", image: "/trophies/9.png" },
      { name: "10", image: "/trophies/10.png" },
      { name: "11", image: "/trophies/11.png" },
      { name: "12", image: "/trophies/12.png" },
      { name: "13", image: "/trophies/13.png" },
      { name: "14", image: "/trophies/14.png" },
      { name: "5", image: "/trophies/5.png" },
      { name: "15", image: "/trophies/15.png" },
      { name: "16", image: "/trophies/16.png" },
      { name: "17", image: "/trophies/17.png" },
      { name: "18", image: "/trophies/18.png" },
    ],
  },
  images: {
    image: "/homeImages/dejavu.jpeg",
    title: "Images",
    linkText: "View More",
  },
  about: {
    image: "/homeImages/about.jpg",
    title: "About",
    linkText: "View More",
  },
  instagram: {
    image: "/homeImages/blur.jpg",
    title: "Arash's Instagram",
    buttonText: "Say hi to me !",
    buttonLink: "https://instagram.com/arash_payam",
  },
  videos: {
    video: "/videos/resume.mp4",
    videoCover: "",
    title: "Youtube",
    linkText: "View More",
    linkAddress: "https://youtube.com/arash-payam",
  },
  contact: {
    phoneText: "Give me a call",
    phoneNo: "+989211808970",
    socials: [
      { name: "instagram", icon: <Instagram />, address: "https://instagram.com/arash_payam" },
      { name: "telegram", icon: <Telegram />, address: "https://telegram.me/arash_payam" },
      { name: "fiveHundred", icon: <FiveHundred />, address: "https://500px.com/old-fox" },
      { name: "unsplash", icon: <Unsplash />, address: "" },
    ],
  },
};
// ---------------------- change about data from here ------------------------
export const aboutData = {
  title: "About",
  description:
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore nam at velit, corporis quod molestiae sed magnam et harum quis illum voluptatibus! Velit, delectus cum laborum odio fuga eaque expedita.",
  images: [
    { name: "left", imageAddress: "/about/left.jpg" },
    { name: "middle", imageAddress: "/about/middle.jpg" },
    { name: "right", imageAddress: "/about/right.jpg" },
  ],
};

// ---------------------- change gallery data from here ------------------------
export const galleryData = [
  { name: "Lonely in crowd", className: "vertical", url: "/workImages/01-lonleyInCrowd-v.JPG" },
  { name: "Ghost in town", className: "vertical", url: "/workImages/02-ghostInTown-v.JPG" },
  { name: "I'm done", className: "horizontal", url: "/workImages/03-imDone-h.jpg" },
  { name: "Roof of the sky", className: "vertical", url: "/workImages/04-roofOfTheSky.JPG" },
  { name: "The beach", className: "", url: "/workImages/05-theBeach.JPG" },
  { name: "Lonely ship", className: "", url: "/workImages/06-lonleyShip.jpeg" },
  { name: "Sad girl", className: "", url: "/workImages/07-sadGril.jpg" },
  { name: "Neon night", className: "vertical", url: "/workImages/08-neonNight-v.JPG" },
  { name: "Freedom", className: "", url: "/workImages/09-freedom.jpg" },
  { name: "An old man", className: "vertical", url: "/workImages/10-anOldman-v.jpg" },
  { name: "Into the tunnel", className: "", url: "/workImages/11-intoTheTunnel.jpeg" },
  { name: "No way!", className: "vertical", url: "/workImages/12-noWay-v.JPG" },
  { name: "Into the heaven", className: "vertical", url: "/workImages/13-intoTheHeaven-v.JPG" },
  { name: "Look up", className: "vertical", url: "/workImages/14-lookUp-v.jpg" },
  { name: "Break from the world", className: "", url: "/workImages/15-breakFromTheWorld-h.jpeg" },
  { name: "Ship is down", className: "vertical", url: "/workImages/16-shipIsDown-v.jpg" },
  { name: "Breathe", className: "horizontal", url: "/workImages/17-breath-h.jpeg" },
  { name: "The alley", className: "", url: "/workImages/18-the alley.jpeg" },
  { name: "Fast road", className: "vertical", url: "/workImages/19-fastRoad.JPG" },
  { name: "The moon", className: "vertical", url: "/workImages/20-theMoon-v.png" },
  { name: "Theater house", className: "vertical", url: "/workImages/21-theaterHouse-v.jpg" },
  { name: "Dejavu", className: "", url: "/workImages/22-dejaVu.jpeg" },
  { name: "Fisherman", className: "vertical", url: "/workImages/23-fisherman-v.jpeg" },
  { name: "Ghost girl", className: "vertical", url: "/workImages/24-ghostGirl-v.JPG" },
  { name: "Textures", className: "horizontal", url: "/workImages/25-textures-h.jpg" },
  { name: "Dancing shadows", className: "vertical", url: "/workImages/26-dancingShadows-v.JPG" },
  { name: "Raging tower", className: "", url: "/workImages/27-ragingTower.JPG" },
  { name: "An old man", className: "vertical", url: "/workImages/28-anOldman-v.jpg" },
  { name: "Cozy corner", className: "vertical", url: "/workImages/29-cozyCorner.jpg" },
  { name: "What if", className: "vertical", url: "/workImages/30-whatIf-v.JPG" },
  { name: "The stairs", className: "vertical", url: "/workImages/31-theStairs-v.jpg" },
  { name: "An empty way", className: "vertical", url: "/workImages/32-anEmptyWay-v.JPG" },
  { name: "The light", className: "", url: "/workImages/33-theLight.JPG" },
  { name: "A horse with no name", className: "vertical", url: "/workImages/34-aHorseWithNoName-v.JPG" },
  { name: "Dancing fire", className: "vertical", url: "/workImages/35-dancingFire-v.jpg" },
  { name: "Khayam", className: "horizontal", url: "/workImages/36-khayam-h.jpg" },
  { name: "Lonely boat", className: "vertical", url: "/workImages/37-lonleyBoat-v.JPG" },
  { name: "Cold building", className: "horizontal", url: "/workImages/38-coldBulding-h.jpeg" },
  { name: "The wish", className: "", url: "/workImages/39-theWish.JPG" },
  { name: "Sky is hight", className: "", url: "/workImages/40-skyIsHigh.jpg" },
  { name: "Subway", className: "", url: "/workImages/subway.jpeg" },
  { name: "The sea", className: "", url: "/workImages/theSea.jpg" },
];
